三、时间信息

3.1 获取每月销量
如果本月本车型没有销量，那么销量为0

3.2 已销售时间
计算本车型已经销售的时间
如果从2012年1月至今销量为0，那么本车在本月还为上市，直到有销量的月份，已销售时间设为1，并随之间增长

3.3 上月总销量与本车型销量

3.4 去年总销量与本车型销量

3.5 本月共有多少种车型在销售

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
def ignore_warn(*args, **kwargs):
    pass
warnings.warn = ignore_warn

In [2]:
train = pd.read_csv('../../raw/CarsSaleForecast/[new] yancheng_train_20171226.csv')
test = pd.read_csv('../../raw/CarsSaleForecast/yancheng_testA_20171225.csv')
trainFeature = pd.read_csv('../../raw/LiChuan/train_feature.csv')

In [3]:
trainDate = train[['sale_date', 'sale_quantity', 'class_id']]
trainDate = trainDate.groupby(['sale_date', 'class_id']).agg('sum').reset_index()
trainDate['year'] = trainDate['sale_date'].apply(lambda x: int(str(x)[0:4]))
trainDate['month'] = trainDate['sale_date'].apply(lambda x: int(str(x)[4:6]))
# trainDate = trainDate.drop(['sale_date'], axis=1)
trainDate.head()

   sale_date  class_id  sale_quantity  year  month
0     201201    125403             90  2012      1
1     201201    136916            665  2012      1
2     201201    178529           1739  2012      1
3     201201    194450             65  2012      1
4     201201    198427             47  2012      1

In [7]:
trainDate

      sale_date  class_id  sale_quantity  year  month
0        201201    125403             90  2012      1
1        201201    136916            665  2012      1
2        201201    178529           1739  2012      1
3        201201    194450             65  2012      1
4        201201    198427             47  2012      1
5        201201    209945            168  2012      1
6        201201    248352           1713  2012      1
7        201201    281301            965  2012      1
8        201201    290854            632  2012      1
9        201201    291086            507  2012      1
10       201201    304458            499  2012      1
11       201201    321683            478  2012      1
12       201201    349023           2522  2012      1
13       201201    354068            460  2012      1
14       201201    379876            245  2012      1
15       201201    384924            738  2012      1
16       201201    395234            102  2012      1
17       201201    409854            120  2012      1
18       201201    425432           1994  2012      1
19       201201    453752             96  2012      1
20       201201    468392            969  2012      1
21       201201    472603            319  2012      1
22       201201    482497            182  2012      1
23       201201    527809            199  2012      1
24       201201    559132            428  2012      1
25       201201    576298            301  2012      1
26       201201    580470            467  2012      1
27       201201    580634            506  2012      1
28       201201    597927           1321  2012      1
29       201201    603972            513  2012      1
...         ...       ...            ...   ...    ...
5557     201710    745137            852  2017     10
5558     201710    750340             95  2017     10
5559     201710    760412             66  2017     10
5560     201710    786351            104  2017     10
5561     201710    789290             77  2017     10
5562     201710    810398            114  2017     10
5563     201710    815230            168  2017     10
5564     201710    819061             94  2017     10
5565     201710    842246            121  2017     10
5566     201710    851857            157  2017     10
5567     201710    854079            162  2017     10
5568     201710    854548            122  2017     10
5569     201710    861459            252  2017     10
5570     201710    871642            155  2017     10
5571     201710    872180            127  2017     10
5572     201710    883691            254  2017     10
5573     201710    890189           1302  2017     10
5574     201710    905061            363  2017     10
5575     201710    905745            183  2017     10
5576     201710    914348            483  2017     10
5577     201710    923841            642  2017     10
5578     201710    924154           1192  2017     10
5579     201710    948936             75  2017     10
5580     201710    950264           1231  2017     10
5581     201710    953842           1061  2017     10
5582     201710    961362             73  2017     10
5583     201710    961962             80  2017     10
5584     201710    963845            207  2017     10
5585     201710    973106            108  2017     10
5586     201710    978089            400  2017     10

[5587 rows x 5 columns]

In [10]:
trainSaleDate = trainFeature

# 2012年1月的销量信息
trainTmp = trainDate[(trainDate['year']==2012)&(trainDate['month']==1)]
# trainTmp = trainTmp[trainTmp['month']==1]
trainTmp.loc[:, 'how_many_month_has_sell'] = 1
sale_class_count = len(trainTmp)

trainSaleDate = pd.merge(trainSaleDate, trainTmp, on='class_id', how='left')
trainSaleDate['year'].fillna(2012.0, inplace=True)
trainSaleDate['month'].fillna(1.0, inplace=True)
# trainSaleDate['how_many_month_has_sell'].fillna(0.0, inplace=True)
trainSaleDate.loc[:, 'sale_quantity_total_last_month'] = 0
trainSaleDate.loc[:, 'sale_quantity_this_last_month'] = 0
trainSaleDate.loc[:, 'this_month_sale_class_count'] = sale_class_count

In [11]:
trainSaleDate

,class_id,brand_id_12,brand_id_49,brand_id_68,brand_id_75,brand_id_76,brand_id_98,brand_id_106,brand_id_126,brand_id_236,...,rated_passenger_7-8,rated_passenger_9,sale_date,sale_quantity,year,month,how_many_month_has_sell,sale_quantity_total_last_month,sale_quantity_this_last_month,this_month_sale_class_count
0,125403,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,90.0,2012.0,1.0,1.0,0,0,42
1,136916,0,0,0,0,0,0,1,0,0,...,0,0,201201.0,665.0,2012.0,1.0,1.0,0,0,42
2,178529,0,0,0,0,0,1,0,0,0,...,0,0,201201.0,1739.0,2012.0,1.0,1.0,0,0,42
3,194450,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,65.0,2012.0,1.0,1.0,0,0,42
4,198427,1,0,0,0,0,0,0,0,0,...,0,0,201201.0,47.0,2012.0,1.0,1.0,0,0,42
5,209945,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,168.0,2012.0,1.0,1.0,0,0,42
6,248352,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,1713.0,2012.0,1.0,1.0,0,0,42
7,281301,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,965.0,2012.0,1.0,1.0,0,0,42
8,290854,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,632.0,2012.0,1.0,1.0,0,0,42
9,291086,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,507.0,2012.0,1.0,1.0,0,0,42
10,304458,0,0,0,0,0,0,1,0,0,...,0,0,201201.0,499.0,2012.0,1.0,1.0,0,0,42
11,321683,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,478.0,2012.0,1.0,1.0,0,0,42
12,349023,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,2522.0,2012.0,1.0,1.0,0,0,42
13,354068,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,460.0,2012.0,1.0,1.0,0,0,42
14,379876,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,245.0,2012.0,1.0,1.0,0,0,42
15,384924,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,738.0,2012.0,1.0,1.0,0,0,42
16,395234,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,102.0,2012.0,1.0,1.0,0,0,42
17,409854,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,120.0,2012.0,1.0,1.0,0,0,42
18,425432,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,1994.0,2012.0,1.0,1.0,0,0,42
19,453752,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,96.0,2012.0,1.0,1.0,0,0,42
20,468392,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,969.0,2012.0,1.0,1.0,0,0,42
21,472603,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,319.0,2012.0,1.0,1.0,0,0,42
22,482497,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,182.0,2012.0,1.0,1.0,0,0,42
23,527809,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,199.0,2012.0,1.0,1.0,0,0,42
24,559132,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,428.0,2012.0,1.0,1.0,0,0,42
25,576298,0,0,0,0,0,0,0,0,0,...,1,1,201201.0,301.0,2012.0,1.0,1.0,0,0,42
26,580470,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,467.0,2012.0,1.0,1.0,0,0,42
27,580634,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,506.0,2012.0,1.0,1.0,0,0,42
28,597927,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,1321.0,2012.0,1.0,1.0,0,0,42
29,603972,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,513.0,2012.0,1.0,1.0,0,0,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,760412,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
111,948936,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
112,249875,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
113,302513,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
114,378536,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
115,475895,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
116,501564,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
117,569154,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
118,973106,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
119,527765,0,0,0,0,0,0,0,0,1,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
120,815230,0,1,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
121,890189,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
122,437063,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
123,789290,0,0,0,0,0,0,1,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
124,854548,0,0,0,0,0,0,0,1,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
125,861459,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
126,714150,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
127,169673,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
128,687270,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
129,842246,0,0,1,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
130,340175,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
131,417803,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
132,612523,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
133,872180,0,0,0,0,1,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
134,905061,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
135,725137,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
136,194201,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
137,359378,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
138,376193,0,0,0,0,1,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
139,653436,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42

In [6]:
trainTmp

    sale_date  class_id  sale_quantity  year  month  how_many_month_has_sell
0      201201    125403             90  2012      1                        1
1      201201    136916            665  2012      1                        1
2      201201    178529           1739  2012      1                        1
3      201201    194450             65  2012      1                        1
4      201201    198427             47  2012      1                        1
5      201201    209945            168  2012      1                        1
6      201201    248352           1713  2012      1                        1
7      201201    281301            965  2012      1                        1
8      201201    290854            632  2012      1                        1
9      201201    291086            507  2012      1                        1
10     201201    304458            499  2012      1                        1
11     201201    321683            478  2012      1                        1
12     201201    349023           2522  2012      1                        1
13     201201    354068            460  2012      1                        1
14     201201    379876            245  2012      1                        1
15     201201    384924            738  2012      1                        1
16     201201    395234            102  2012      1                        1
17     201201    409854            120  2012      1                        1
18     201201    425432           1994  2012      1                        1
19     201201    453752             96  2012      1                        1
20     201201    468392            969  2012      1                        1
21     201201    472603            319  2012      1                        1
22     201201    482497            182  2012      1                        1
23     201201    527809            199  2012      1                        1
24     201201    559132            428  2012      1                        1
25     201201    576298            301  2012      1                        1
26     201201    580470            467  2012      1                        1
27     201201    580634            506  2012      1                        1
28     201201    597927           1321  2012      1                        1
29     201201    603972            513  2012      1                        1
30     201201    614059            240  2012      1                        1
31     201201    628041            186  2012      1                        1
32     201201    651347             54  2012      1                        1
33     201201    682651            373  2012      1                        1
34     201201    713651            192  2012      1                        1
35     201201    714152            298  2012      1                        1
36     201201    735971            877  2012      1                        1
37     201201    819061            640  2012      1                        1
38     201201    883691            159  2012      1                        1
39     201201    914348            660  2012      1                        1
40     201201    961362            182  2012      1                        1
41     201201    961962             16  2012      1                        1

In [9]:
trainSaleDate

,class_id,brand_id_12,brand_id_49,brand_id_68,brand_id_75,brand_id_76,brand_id_98,brand_id_106,brand_id_126,brand_id_236,...,rated_passenger_7-8,rated_passenger_9,sale_date,sale_quantity,year,month,how_many_month_has_sell,sale_quantity_total_last_month,sale_quantity_this_last_month,this_month_sale_class_count
0,125403,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,90.0,2012.0,1.0,1.0,0,0,42
1,136916,0,0,0,0,0,0,1,0,0,...,0,0,201201.0,665.0,2012.0,1.0,1.0,0,0,42
2,178529,0,0,0,0,0,1,0,0,0,...,0,0,201201.0,1739.0,2012.0,1.0,1.0,0,0,42
3,194450,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,65.0,2012.0,1.0,1.0,0,0,42
4,198427,1,0,0,0,0,0,0,0,0,...,0,0,201201.0,47.0,2012.0,1.0,1.0,0,0,42
5,209945,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,168.0,2012.0,1.0,1.0,0,0,42
6,248352,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,1713.0,2012.0,1.0,1.0,0,0,42
7,281301,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,965.0,2012.0,1.0,1.0,0,0,42
8,290854,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,632.0,2012.0,1.0,1.0,0,0,42
9,291086,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,507.0,2012.0,1.0,1.0,0,0,42
10,304458,0,0,0,0,0,0,1,0,0,...,0,0,201201.0,499.0,2012.0,1.0,1.0,0,0,42
11,321683,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,478.0,2012.0,1.0,1.0,0,0,42
12,349023,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,2522.0,2012.0,1.0,1.0,0,0,42
13,354068,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,460.0,2012.0,1.0,1.0,0,0,42
14,379876,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,245.0,2012.0,1.0,1.0,0,0,42
15,384924,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,738.0,2012.0,1.0,1.0,0,0,42
16,395234,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,102.0,2012.0,1.0,1.0,0,0,42
17,409854,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,120.0,2012.0,1.0,1.0,0,0,42
18,425432,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,1994.0,2012.0,1.0,1.0,0,0,42
19,453752,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,96.0,2012.0,1.0,1.0,0,0,42
20,468392,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,969.0,2012.0,1.0,1.0,0,0,42
21,472603,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,319.0,2012.0,1.0,1.0,0,0,42
22,482497,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,182.0,2012.0,1.0,1.0,0,0,42
23,527809,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,199.0,2012.0,1.0,1.0,0,0,42
24,559132,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,428.0,2012.0,1.0,1.0,0,0,42
25,576298,0,0,0,0,0,0,0,0,0,...,1,1,201201.0,301.0,2012.0,1.0,1.0,0,0,42
26,580470,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,467.0,2012.0,1.0,1.0,0,0,42
27,580634,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,506.0,2012.0,1.0,1.0,0,0,42
28,597927,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,1321.0,2012.0,1.0,1.0,0,0,42
29,603972,0,0,0,0,0,0,0,0,0,...,0,0,201201.0,513.0,2012.0,1.0,1.0,0,0,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,760412,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
111,948936,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
112,249875,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
113,302513,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
114,378536,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
115,475895,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
116,501564,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
117,569154,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
118,973106,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
119,527765,0,0,0,0,0,0,0,0,1,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
120,815230,0,1,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
121,890189,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
122,437063,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
123,789290,0,0,0,0,0,0,1,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
124,854548,0,0,0,0,0,0,0,1,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
125,861459,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
126,714150,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
127,169673,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
128,687270,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
129,842246,0,0,1,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
130,340175,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
131,417803,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
132,612523,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
133,872180,0,0,0,0,1,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
134,905061,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
135,725137,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
136,194201,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
137,359378,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
138,376193,0,0,0,0,1,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42
139,653436,0,0,0,0,0,0,0,0,0,...,0,0,NaN,NaN,2012.0,1.0,NaN,0,0,42

In [8]:
pd.merge(trainSaleDate, trainTmp, on='class_id', how='left')

,class_id,brand_id_12,brand_id_49,brand_id_68,brand_id_75,brand_id_76,brand_id_98,brand_id_106,brand_id_126,brand_id_236,...,month_x,how_many_month_has_sell_x,sale_quantity_total_last_month,sale_quantity_this_last_month,this_month_sale_class_count,sale_date_y,sale_quantity_y,year_y,month_y,how_many_month_has_sell_y
0,125403,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,90.0,2012.0,1.0,1.0
1,136916,0,0,0,0,0,0,1,0,0,...,1.0,1.0,0,0,42,201201.0,665.0,2012.0,1.0,1.0
2,178529,0,0,0,0,0,1,0,0,0,...,1.0,1.0,0,0,42,201201.0,1739.0,2012.0,1.0,1.0
3,194450,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,65.0,2012.0,1.0,1.0
4,198427,1,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,47.0,2012.0,1.0,1.0
5,209945,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,168.0,2012.0,1.0,1.0
6,248352,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,1713.0,2012.0,1.0,1.0
7,281301,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,965.0,2012.0,1.0,1.0
8,290854,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,632.0,2012.0,1.0,1.0
9,291086,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,507.0,2012.0,1.0,1.0
10,304458,0,0,0,0,0,0,1,0,0,...,1.0,1.0,0,0,42,201201.0,499.0,2012.0,1.0,1.0
11,321683,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,478.0,2012.0,1.0,1.0
12,349023,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,2522.0,2012.0,1.0,1.0
13,354068,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,460.0,2012.0,1.0,1.0
14,379876,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,245.0,2012.0,1.0,1.0
15,384924,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,738.0,2012.0,1.0,1.0
16,395234,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,102.0,2012.0,1.0,1.0
17,409854,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,120.0,2012.0,1.0,1.0
18,425432,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,1994.0,2012.0,1.0,1.0
19,453752,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,96.0,2012.0,1.0,1.0
20,468392,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,969.0,2012.0,1.0,1.0
21,472603,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,319.0,2012.0,1.0,1.0
22,482497,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,182.0,2012.0,1.0,1.0
23,527809,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,199.0,2012.0,1.0,1.0
24,559132,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,428.0,2012.0,1.0,1.0
25,576298,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,301.0,2012.0,1.0,1.0
26,580470,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,467.0,2012.0,1.0,1.0
27,580634,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,506.0,2012.0,1.0,1.0
28,597927,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,1321.0,2012.0,1.0,1.0
29,603972,0,0,0,0,0,0,0,0,0,...,1.0,1.0,0,0,42,201201.0,513.0,2012.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,760412,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
111,948936,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
112,249875,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
113,302513,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
114,378536,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
115,475895,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
116,501564,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
117,569154,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
118,973106,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
119,527765,0,0,0,0,0,0,0,0,1,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
120,815230,0,1,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
121,890189,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
122,437063,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
123,789290,0,0,0,0,0,0,1,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
124,854548,0,0,0,0,0,0,0,1,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
125,861459,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
126,714150,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
127,169673,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
128,687270,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
129,842246,0,0,1,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
130,340175,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
131,417803,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
132,612523,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
133,872180,0,0,0,0,1,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
134,905061,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
135,725137,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
136,194201,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
137,359378,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
138,376193,0,0,0,0,1,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN
139,653436,0,0,0,0,0,0,0,0,0,...,1.0,NaN,0,0,42,NaN,NaN,NaN,NaN,NaN

In [5]:
sale_class_count

42

In [5]:
for month in range(2, 13):
    trainSaleDateTmp = trainFeature
    trainTmp = trainDate[(trainDate['year']==2012)&(trainDate['month']==month)]
    
    sellmonth = trainSaleDate[['class_id', 'how_many_month_has_sell', 'sale_quantity']][(trainSaleDate['year']==2012)&(trainSaleDate['month']==(month-1))]
    sellmonth.dropna(inplace=True)
    sellmonth['how_many_month_has_sell'] = sellmonth['how_many_month_has_sell']+1
    sale_quantity_total_last_month = sellmonth['sale_quantity'].sum()
    sellmonth.rename(columns={'sale_quantity': 'sale_quantity_this_last_month'}, inplace=True)
    
    trainTmp = pd.merge(trainTmp, sellmonth, on='class_id', how='left')
    trainTmp['how_many_month_has_sell'].fillna(1.0, inplace=True)
    sale_class_count = len(trainTmp)
    
    trainSaleDateTmp = pd.merge(trainSaleDateTmp, trainTmp, on='class_id', how='left')
    trainSaleDateTmp['year'].fillna(2012.0, inplace=True)
    trainSaleDateTmp['month'].fillna(month, inplace=True)
    trainSaleDateTmp.loc[:, 'sale_quantity_total_last_month'] = sale_quantity_total_last_month
    trainSaleDateTmp.loc[:, 'this_month_sale_class_count'] = sale_class_count
    
    trainSaleDate = pd.concat([trainSaleDate, trainSaleDateTmp])
    
trainSaleDate.loc[:, 'sale_quantity_total_last_year'] = 0
trainSaleDate.loc[:, 'sale_quantity_this_last_year'] = 0

In [6]:
for year in range(2013, 2017):
    for month in range(1, 13):
        trainSaleDateTmp = trainFeature
        trainTmp = trainDate[(trainDate['year']==year)&(trainDate['month']==month)]
        
        if month == 1:
            sellmonth = trainSaleDate[['class_id', 'how_many_month_has_sell', 'sale_quantity']][(trainSaleDate['year']==(year-1))&(trainSaleDate['month']==12)]
        else:
            sellmonth = trainSaleDate[['class_id', 'how_many_month_has_sell', 'sale_quantity']][(trainSaleDate['year']==year)&(trainSaleDate['month']==(month-1))]
        sellmonth.dropna(inplace=True)
        sellmonth['how_many_month_has_sell'] = sellmonth['how_many_month_has_sell']+1
        sale_quantity_total_last_month = sellmonth['sale_quantity'].sum()
        sellmonth.rename(columns={'sale_quantity': 'sale_quantity_this_last_month'}, inplace=True)
        
        sellYear = trainSaleDate[['class_id', 'sale_quantity']][((trainSaleDate['year']==(year-1))&(trainSaleDate['month']>=month))|((trainSaleDate['year']==year)&(trainSaleDate['month']<month))]
        sellYear.dropna(inplace=True)
        sellYear = sellYear.groupby('class_id').agg('sum').reset_index()
        sale_quantity_total_last_year = sellYear['sale_quantity'].sum()
        sellYear.rename(columns={'sale_quantity': 'sale_quantity_this_last_year'}, inplace=True)
        
        trainTmp = pd.merge(trainTmp, sellmonth, on='class_id', how='left')
        trainTmp['how_many_month_has_sell'].fillna(1.0, inplace=True)
        sale_class_count = len(trainTmp)
        
        trainTmp = pd.merge(trainTmp, sellYear, on='class_id', how='left')
        
        trainSaleDateTmp = pd.merge(trainSaleDateTmp, trainTmp, on='class_id', how='left')
        trainSaleDateTmp['year'].fillna(year, inplace=True)
        trainSaleDateTmp['month'].fillna(month, inplace=True)
        trainSaleDateTmp.loc[:, 'sale_quantity_total_last_month'] = sale_quantity_total_last_month
        trainSaleDateTmp.loc[:, 'sale_quantity_total_last_year'] = sale_quantity_total_last_year
        trainSaleDateTmp.loc[:, 'this_month_sale_class_count'] = sale_class_count
        
        trainSaleDate = pd.concat([trainSaleDate, trainSaleDateTmp])
        
trainSaleDate.head()

,TR_0,TR_1,TR_4,TR_5,TR_5;4,TR_6,TR_7,TR_8,TR_8;7,TR_9,...,total_quality_mean,total_quality_min,type_id_1,type_id_2,type_id_3,type_id_4,wheelbase_max,wheelbase_mean,wheelbase_min,year
0,0,0,0,0,0,1,0,0,0,0,...,0.945055,0.880342,0,0,1,0,0.973262,0.973262,0.973262,2012.0
1,1,0,1,1,0,1,0,0,0,0,...,0.621083,0.555556,0,1,0,0,0.554813,0.554813,0.554813,2012.0
2,0,0,0,1,0,0,0,0,0,0,...,0.269231,0.170940,0,0,0,1,0.521390,0.354278,0.187166,2012.0
3,0,0,1,1,0,1,1,0,0,0,...,0.559829,0.461538,1,0,0,0,0.414439,0.387701,0.360963,2012.0
4,0,0,1,1,0,1,0,0,0,0,...,0.227066,0.222222,0,1,0,0,0.323529,0.322193,0.320856,2012.0

In [7]:
for year in range(2017, 2018):
    for month in range(1, 11):
        trainSaleDateTmp = trainFeature
        trainTmp = trainDate[trainDate['year']==year]
        trainTmp = trainTmp[trainTmp['month']==month]
        
        if month == 1:
            sellmonth = trainSaleDate[['class_id', 'how_many_month_has_sell', 'sale_quantity']][(trainSaleDate['year']==(year-1))&(trainSaleDate['month']==12)]
        else:
            sellmonth = trainSaleDate[['class_id', 'how_many_month_has_sell', 'sale_quantity']][(trainSaleDate['year']==year)&(trainSaleDate['month']==(month-1))]
        sellmonth.dropna(inplace=True)
        sellmonth['how_many_month_has_sell'] = sellmonth['how_many_month_has_sell']+1
        sale_quantity_total_last_month = sellmonth['sale_quantity'].sum()
        sellmonth.rename(columns={'sale_quantity': 'sale_quantity_this_last_month'}, inplace=True)
        
        sellYear = trainSaleDate[['class_id', 'sale_quantity']][((trainSaleDate['year']==(year-1))&(trainSaleDate['month']>=month))|((trainSaleDate['year']==year)&(trainSaleDate['month']<month))]
        sellYear.dropna(inplace=True)
        sellYear = sellYear.groupby('class_id').agg('sum').reset_index()
        sale_quantity_total_last_year = sellYear['sale_quantity'].sum()
        sellYear.rename(columns={'sale_quantity': 'sale_quantity_this_last_year'}, inplace=True)
        
        trainTmp = pd.merge(trainTmp, sellmonth, on='class_id', how='left')
        trainTmp['how_many_month_has_sell'].fillna(1.0, inplace=True)
        sale_class_count = len(trainTmp)
        
        trainTmp = pd.merge(trainTmp, sellYear, on='class_id', how='left')
        
        trainSaleDateTmp = pd.merge(trainSaleDateTmp, trainTmp, on='class_id', how='left')
        trainSaleDateTmp['year'].fillna(year, inplace=True)
        trainSaleDateTmp['month'].fillna(month, inplace=True)
        trainSaleDateTmp.loc[:, 'sale_quantity_total_last_month'] = sale_quantity_total_last_month
        trainSaleDateTmp.loc[:, 'sale_quantity_total_last_year'] = sale_quantity_total_last_year
        trainSaleDateTmp.loc[:, 'this_month_sale_class_count'] = sale_class_count
        
        trainSaleDate = pd.concat([trainSaleDate, trainSaleDateTmp])

In [8]:
trainSaleDate.sort_values(['year', 'month', 'class_id'])
trainSaleDate.fillna(0.0, inplace=True)
trainSaleDate.to_csv('../../raw/LiChuan/trainSaleDate.csv', index=False)

In [9]:
# trainSaleDate['year'] = trainSaleDate['year'].astype('int32')
# trainSaleDate['mouth'] = trainSaleDate['mouth'].astype('int32')
# trainSaleDate2 = trainSaleDate[(trainSaleDate.year != 2012)]

In [ ]:
# trainSaleDate2.to_csv('../../raw/LiChuan/trainSaleDate2.csv', index=False)